version: '3.8'
services:
  mysql:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=""
    restart: unless-stopped
    container_name: isanteplus-mysql
    hostname: isanteplus-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: "exit 0"
    environment:
      - MYSQL_DATABASE=openmrs
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_ROOT_HOST=%    # Allow docker containers to connect to mysql
    volumes:
      # - ./db/mysql.cnf:/etc/mysql/conf.d/custom.cnf  # mysql config preconfigured to allow binlog/debezium
      - data:/var/lib/mysql
    networks:
      - isanteplus
    
  isanteplus:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./openmrs-server/Dockerfile
      args:
        USERNAME: ${RELEASE_USERNAME}
        TOKEN: ${RELEASE_TOKEN}
        ISANTEPLUS_VERSION: ${ISANTEPLUS_VERSION}
    container_name: isanteplus
    hostname: isanteplus
    ports:
      - "${ISANTEPLUS_PORT}:8080"
    healthcheck:
      test: "exit 0"
    environment:
      OMRS_JAVA_MEMORY_OPTS: -Xmx2048m -Xms1024m -XX:NewSize=128m
      OMRS_CONFIG_CONNECTION_SERVER: isanteplus-mysql
      OMRS_CONFIG_CREATE_DATABASE_USER: 'false'
      OMRS_CONFIG_CREATE_TABLES: 'true'
      OMRS_CONFIG_ADD_DEMO_DATA: 'false'
      OMRS_CONFIG_CONNECTION_URL: jdbc:mysql://isanteplus-mysql:3306/openmrs?autoReconnect=true
      OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE: 'true'
      OMRS_JAVA_SERVER_OPTS: -Dfile.encoding=UTF-8 -server -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -Djava.awt.headlesslib=true
      OMRS_CONFIG_CONNECTION_USERNAME: mysqluser
      OMRS_CONFIG_CONNECTION_PASSWORD: mysqlpw
      JPDA_ADDRESS: 0.0.0.0:8000
      JPDA_TRANSPORT: dt_socket
      OMRS_DEV_DEBUG_PORT: 8000
    volumes:
      - openmrs-data:/openmrs/data
    networks:
      - isanteplus

networks:
  isanteplus:
volumes:
  data:
  openmrs-data:


