# For every commit or tag that is pushed, but image from it and push this to docker hub

name: Build and Deploy

on:
  release:
    types: [published]
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ISANTEPLUS_VERSION: 2.9.1

jobs:
  deploy:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.RELEASE_USERNAME }}
      TOKEN: ${{ secrets.RELEASE_TOKEN }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            ISANTEPLUS_VERSION=${{ env.ISANTEPLUS_VERSION }}
            USERNAME=${{ secrets.RELEASE_USERNAME }}
            TOKEN=${{ secrets.RELEASE_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline